service: one

provider:
  name: aws
  runtime: nodejs12.x
  stage: tudn
  region: us-east-1

functions:
  int:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
