service: One-TUDN

provider:
  name: aws
  runtime: nodejs14.x
  stage: int
  region: us-east-1

functions:
  Webapp:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 256 # mb
    events:
      - http:
          path: One-TUDN
          method: post
          cors: false
          async: false
          private: false