service: One-tudn

provider:
  name: aws
  runtime: nodejs14.x
  stage: Integration
  region: us-east-1

functions:
  Webapp:
    handler: src/handler.webapp
    name: one-tudn-int
    timeout: 30 # seconds
    memorySize: 128 # mb
    #events:
      #- http:
          #method: GET
          #path: /One-TUDN 
          