service: One-TUDN

provider:
  name: aws
  runtime: nodejs14.x
  stage: int
  region: us-east-1

functions:
  Webapp:
    handler: src/handler.webapp
    name: One-TUDN-int-Webapp
    timeout: 30 # seconds
    memorySize: 128 # mb
    events:
      - http:
          name: int-One-TUDN
          method: GET
          path: /One-TUDN 
          